[package]
name = "ngkg-agent-catalog-migrator"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ngkg-agent-catalog = { path = "../../crates/ngkg-agent-catalog" }
tokio.workspace = true

[lints]
workspace = true
