#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require_command() {
  if ! command -v "$1" >/dev/null; then
    echo "required qualification command is unavailable: $1" >&2
    exit 2
  fi
}

require_command cargo
require_command helm
if [[ ! -s "${ROOT}/Cargo.lock" ]]; then
  echo "Cargo.lock is mandatory and has not been generated by the controlled Rust build" >&2
  exit 2
fi

cd "${ROOT}"
cargo fmt --check
cargo check --locked --workspace --all-targets
cargo test --locked --workspace
cargo clippy --locked --workspace --all-targets -- -D warnings

cd "${ROOT}"
helm lint charts/ngkg-agents -f charts/ngkg-agents/examples/production-values.yaml
helm template ngkg-agents charts/ngkg-agents \
  --namespace ngkg \
  -f charts/ngkg-agents/examples/production-values.yaml >/dev/null

echo "NGKG MCP Agent 0.10.0 native acceptance: PASS"
