FROM gcr.io/distroless/cc-debian12:nonroot
COPY ngkg-storage-recovery-operator /usr/local/bin/ngkg-storage-recovery-operator
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/ngkg-storage-recovery-operator"]
