platform: {kubernetesDistribution: rke}
hpcNodeGroups: {provisioner: cluster-autoscaler}
nodeProvisioning:
  provider: rancher-cluster-autoscaler
  namespace: kube-system
  workloadName: cluster-autoscaler
  credentialSecret: rancher-cluster-autoscaler-cloud-config
  discoveryResource: management.cattle.io/v3/nodes
