//! Bounded-memory, topology-independent compilation of verified cloud RDF fragments.
//!
//! Phase 40.13.12 consumes the checksum-bound N-Quads handoff created by the
//! cloud source decoder. It never lists a bucket, accepts credentials, aligns
//! raw data, authorizes graphs, or activates a snapshot. Kubernetes pod count
//! changes scheduling only: immutable fragment ordinals and logical partition
//! IDs determine every output byte.

use std::{
    cmp::Reverse,
    collections::{BTreeMap, BTreeSet, BinaryHeap},
    fs::{self, File, OpenOptions},
    io::{BufRead, BufReader, BufWriter, Read, Write},
    path::{Path, PathBuf},
    sync::Arc,
};

use arrow_array::{ArrayRef, RecordBatch, StringArray, UInt64Array, UInt8Array};
use arrow_schema::{DataType, Field, Schema};
use oxigraph::{
    io::{RdfFormat, RdfParser},
    model::{BlankNode, GraphName, Quad, Subject, Term},
};
use parquet::{arrow::ArrowWriter, file::properties::WriterProperties};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;
use uuid::Uuid;

/// Phase 40.13.12 semantic compilation contract version.
pub const SEMANTIC_COMPILER_FORMAT_VERSION: u32 = 1;
/// Graph namespace used by the C8 Next Generation platform.
pub const GRAPH_NAMESPACE: &str = "https://c8-next-generation.io/";
const EXTERNAL_MERGE_FAN_IN: usize = 256;

/// One verified decoded fragment from the Phase 40.13.11 handoff.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct DecodedFragment {
    pub ordinal: u32,
    pub source_object_key: String,
    pub source_sha256: String,
    pub blank_node_scope: String,
    pub object_key: String,
    pub sha256: String,
    pub bytes: u64,
    pub quad_count: u64,
}

/// Checksum-bound input created only after all cloud decoder completions verify.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct CompilerHandoffManifest {
    pub format_version: u32,
    pub tenant_id: Uuid,
    pub dataset_id: Uuid,
    pub operation_id: Uuid,
    pub target_snapshot_id: Uuid,
    pub source_manifest_object_key: String,
    pub source_manifest_sha256: String,
    pub decode_plan_object_key: String,
    pub decode_plan_sha256: String,
    pub aggregate_source_sha256: String,
    pub logical_partitions: u32,
    pub decoded_format: String,
    pub blank_node_policy: String,
    pub total_objects: u32,
    pub total_bytes: u64,
    pub total_quads: u64,
    pub expected_completions: u32,
    pub verified_completions: u32,
    pub completion_set_sha256: String,
    pub fragments: Vec<DecodedFragment>,
}

/// Immutable file emitted by one map completion.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct RunArtifact {
    pub relative_path: String,
    pub sha256: String,
    pub bytes: u64,
    pub row_count: u64,
}

/// Bounded external-sort output for one decoded source object.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct FragmentMapManifest {
    pub format_version: u32,
    pub dataset_id: Uuid,
    pub snapshot_id: Uuid,
    pub compiler_handoff_sha256: String,
    pub aggregate_source_sha256: String,
    pub fragment_ordinal: u32,
    pub fragment_sha256: String,
    pub blank_node_scope: String,
    pub logical_partitions: u32,
    pub input_quad_count: u64,
    pub unique_quad_count: u64,
    pub fact_runs: BTreeMap<u32, Vec<RunArtifact>>,
    pub term_runs: Vec<RunArtifact>,
}

/// Global dense RDF term dictionary produced by an all-map barrier.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct DictionaryManifest {
    pub format_version: u32,
    pub dataset_id: Uuid,
    pub snapshot_id: Uuid,
    pub compiler_handoff_sha256: String,
    pub map_completion_set_sha256: String,
    pub dictionary_path: String,
    pub dictionary_sha256: String,
    pub term_count: u64,
    pub guid_dictionary_path: String,
    pub guid_dictionary_sha256: String,
    pub entity_count: u64,
    pub verified_map_completions: u32,
}

/// Physical graph category. This is classification, never authorization.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum GraphRole {
    PhysicalDefault,
    AssertedOntologyCandidate,
    ClosureArtifact,
    ProvenanceArtifact,
    NamedRdf,
}

/// Inactive graph inventory entry generated by a partition reducer.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct GraphInventoryEntry {
    pub graph_term: String,
    pub graph_id: u64,
    pub role: GraphRole,
    pub quad_count: u64,
    pub union_default_candidate: bool,
    pub asserted_ontology_candidate: bool,
    pub qualification_required: bool,
}

/// Immutable evidence and artifacts emitted by one logical partition reducer.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct SemanticPartitionManifest {
    pub format_version: u32,
    pub dataset_id: Uuid,
    pub snapshot_id: Uuid,
    pub compiler_handoff_sha256: String,
    pub dictionary_sha256: String,
    pub partition_index: u32,
    pub partition_id: String,
    pub input_run_count: u32,
    pub fact_count: u64,
    pub duplicate_fact_count: u64,
    pub edge_count: u64,
    pub class_assertion_count: u64,
    pub artifacts: Vec<RunArtifact>,
    pub graph_inventory: Vec<GraphInventoryEntry>,
    pub semantic_content_sha256: String,
}

/// Complete but inactive semantic compilation root.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct SemanticCompilationRoot {
    pub format_version: u32,
    pub tenant_id: Uuid,
    pub dataset_id: Uuid,
    pub operation_id: Uuid,
    pub snapshot_id: Uuid,
    pub compiler_handoff_sha256: String,
    pub aggregate_source_sha256: String,
    pub dictionary_manifest_path: String,
    pub dictionary_manifest_sha256: String,
    pub logical_partitions: u32,
    pub partitions: Vec<PartitionReference>,
    pub fact_count: u64,
    pub duplicate_fact_count: u64,
    pub edge_count: u64,
    pub class_assertion_count: u64,
    pub graph_inventory: Vec<GraphInventoryEntry>,
    pub union_default_candidates: Vec<String>,
    pub asserted_ontology_candidates: Vec<String>,
    pub authorization_state: String,
    pub qualification_state: String,
    pub publication_state: String,
    pub semantic_content_sha256: String,
}

/// One checksum-bound logical partition in the compilation root.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct PartitionReference {
    pub partition_index: u32,
    pub partition_id: String,
    pub manifest_path: String,
    pub manifest_sha256: String,
    pub fact_count: u64,
}

/// Resource bounds for fragment mapping.
#[derive(Clone, Copy, Debug)]
pub struct MapLimits {
    pub max_fragment_bytes: u64,
    pub max_fragment_quads: u64,
    pub max_rows_in_memory: usize,
    pub max_run_bytes: u64,
    /// Bounded parser lanes inside one cgroup-aware mapper pod.
    pub worker_threads: usize,
}

/// Resource bounds for one partition reducer.
#[derive(Clone, Copy, Debug)]
pub struct ReduceLimits {
    pub max_input_runs: usize,
    pub max_partition_quads: u64,
    pub parquet_row_group_rows: usize,
}

/// Fail-closed semantic compiler failures.
#[derive(Debug, Error)]
pub enum SemanticCompilerError {
    #[error("semantic compiler I/O failed: {0}")]
    Io(#[from] std::io::Error),
    #[error("semantic compiler JSON failed: {0}")]
    Json(#[from] serde_json::Error),
    #[error("semantic compiler RDF failed: {0}")]
    Rdf(String),
    #[error("semantic compiler Arrow failed: {0}")]
    Arrow(#[from] arrow_schema::ArrowError),
    #[error("semantic compiler Parquet failed: {0}")]
    Parquet(#[from] parquet::errors::ParquetError),
    #[error("semantic compiler contract failed: {0}")]
    Contract(String),
    #[error("immutable output already exists: {0}")]
    ImmutableConflict(PathBuf),
}

/// Validate the complete Phase 40.13.11 handoff before scheduling any work.
pub fn validate_handoff(
    handoff: &CompilerHandoffManifest,
) -> Result<(), SemanticCompilerError> {
    if handoff.format_version != 1
        || handoff.decoded_format != "application/n-quads"
        || handoff.blank_node_policy != "object-scoped-label-v1"
        || handoff.logical_partitions == 0
        || handoff.logical_partitions > 65_536
        || handoff.total_objects == 0
        || handoff.total_quads == 0
        || handoff.expected_completions != handoff.verified_completions
    {
        return Err(SemanticCompilerError::Contract(
            "compiler handoff header or completion barrier is invalid".to_owned(),
        ));
    }
    for checksum in [
        &handoff.source_manifest_sha256,
        &handoff.decode_plan_sha256,
        &handoff.aggregate_source_sha256,
        &handoff.completion_set_sha256,
    ] {
        require_sha256(checksum)?;
    }
    if handoff.fragments.len() != usize::try_from(handoff.total_objects).unwrap_or(usize::MAX) {
        return Err(SemanticCompilerError::Contract(
            "handoff fragment count is not totalObjects".to_owned(),
        ));
    }
    let mut bytes = 0_u64;
    let mut quads = 0_u64;
    for (index, fragment) in handoff.fragments.iter().enumerate() {
        if usize::try_from(fragment.ordinal).ok() != Some(index)
            || !valid_blank_scope(&fragment.blank_node_scope, fragment.ordinal)
        {
            return Err(SemanticCompilerError::Contract(
                "handoff fragment ordinals or blank-node scopes are invalid".to_owned(),
            ));
        }
        require_sha256(&fragment.source_sha256)?;
        require_sha256(&fragment.sha256)?;
        bytes = bytes.checked_add(fragment.bytes).ok_or_else(|| {
            SemanticCompilerError::Contract("fragment byte total overflow".to_owned())
        })?;
        quads = quads.checked_add(fragment.quad_count).ok_or_else(|| {
            SemanticCompilerError::Contract("fragment quad total overflow".to_owned())
        })?;
    }
    if bytes != handoff.total_bytes || quads != handoff.total_quads {
        return Err(SemanticCompilerError::Contract(
            "handoff fragment totals do not match the barrier".to_owned(),
        ));
    }
    Ok(())
}

/// Map one verified decoded fragment into bounded, sorted logical-partition runs.
pub fn map_fragment(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    fragment_ordinal: u32,
    fragment_path: &Path,
    output_root: &Path,
    limits: MapLimits,
) -> Result<PathBuf, SemanticCompilerError> {
    validate_handoff(handoff)?;
    require_sha256(handoff_sha256)?;
    if limits.max_fragment_bytes == 0
        || limits.max_fragment_quads == 0
        || limits.max_rows_in_memory == 0
        || limits.max_run_bytes == 0
        || limits.worker_threads == 0
    {
        return Err(SemanticCompilerError::Contract(
            "map resource limits must be positive".to_owned(),
        ));
    }
    let fragment = handoff
        .fragments
        .get(usize::try_from(fragment_ordinal).map_err(|_| {
            SemanticCompilerError::Contract("fragment ordinal overflow".to_owned())
        })?)
        .filter(|value| value.ordinal == fragment_ordinal)
        .ok_or_else(|| SemanticCompilerError::Contract("fragment is absent".to_owned()))?;
    verify_file(fragment_path, &fragment.sha256, Some(fragment.bytes))?;
    if fragment.bytes > limits.max_fragment_bytes || fragment.quad_count > limits.max_fragment_quads {
        return Err(SemanticCompilerError::Contract(
            "fragment exceeds configured map ceiling".to_owned(),
        ));
    }
    ensure_new_root(output_root)?;
    let partition_count = usize::try_from(handoff.logical_partitions)
        .map_err(|_| SemanticCompilerError::Contract("partition count overflow".to_owned()))?;
    let mut buffers = vec![Vec::<String>::new(); partition_count];
    let mut term_buffer = Vec::<String>::new();
    let mut fact_runs = BTreeMap::<u32, Vec<RunArtifact>>::new();
    let mut term_runs = Vec::<RunArtifact>::new();
    let mut quad_count = 0_u64;
    let mut run_ordinal = 0_u32;
    let mut term_run_ordinal = 0_u32;
    let mut batch = Vec::with_capacity(limits.max_rows_in_memory);
    for line in BufReader::new(File::open(fragment_path)?).lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        batch.push(line);
        if batch.len() == limits.max_rows_in_memory {
            process_map_batch(
                &batch,
                &fragment.blank_node_scope,
                handoff.logical_partitions,
                limits.worker_threads,
                &mut buffers,
                &mut term_buffer,
            )?;
            quad_count = checked_add(
                quad_count,
                u64::try_from(batch.len()).map_err(|_| {
                    SemanticCompilerError::Contract("batch row count overflow".to_owned())
                })?,
                "mapped quad",
            )?;
            if quad_count > limits.max_fragment_quads {
                return Err(SemanticCompilerError::Contract(
                    "fragment exceeded quad ceiling while parsing".to_owned(),
                ));
            }
            flush_fact_buffers(output_root, &mut buffers, &mut fact_runs, &mut run_ordinal)?;
            flush_term_buffer(
                output_root,
                &mut term_buffer,
                &mut term_runs,
                &mut term_run_ordinal,
            )?;
            batch.clear();
        }
    }
    if !batch.is_empty() {
        process_map_batch(
            &batch,
            &fragment.blank_node_scope,
            handoff.logical_partitions,
            limits.worker_threads,
            &mut buffers,
            &mut term_buffer,
        )?;
        quad_count = checked_add(
            quad_count,
            u64::try_from(batch.len()).map_err(|_| {
                SemanticCompilerError::Contract("batch row count overflow".to_owned())
            })?,
            "mapped quad",
        )?;
    }
    flush_fact_buffers(
        output_root,
        &mut buffers,
        &mut fact_runs,
        &mut run_ordinal,
    )?;
    flush_term_buffer(
        output_root,
        &mut term_buffer,
        &mut term_runs,
        &mut term_run_ordinal,
    )?;
    if quad_count != fragment.quad_count {
        return Err(SemanticCompilerError::Contract(
            "mapped quad count differs from verified fragment".to_owned(),
        ));
    }
    let unique_quad_count = fact_runs
        .values()
        .flatten()
        .try_fold(0_u64, |total, run| total.checked_add(run.row_count))
        .ok_or_else(|| SemanticCompilerError::Contract("unique quad count overflow".to_owned()))?;
    if fact_runs
        .values()
        .flatten()
        .chain(term_runs.iter())
        .any(|run| run.bytes > limits.max_run_bytes)
    {
        return Err(SemanticCompilerError::Contract(
            "map spill run exceeds configured byte ceiling".to_owned(),
        ));
    }
    let manifest = FragmentMapManifest {
        format_version: SEMANTIC_COMPILER_FORMAT_VERSION,
        dataset_id: handoff.dataset_id,
        snapshot_id: handoff.target_snapshot_id,
        compiler_handoff_sha256: handoff_sha256.to_owned(),
        aggregate_source_sha256: handoff.aggregate_source_sha256.clone(),
        fragment_ordinal,
        fragment_sha256: fragment.sha256.clone(),
        blank_node_scope: fragment.blank_node_scope.clone(),
        logical_partitions: handoff.logical_partitions,
        input_quad_count: quad_count,
        unique_quad_count,
        fact_runs,
        term_runs,
    };
    let manifest_path = output_root.join("fragment-map.json");
    write_json_new(&manifest_path, &manifest)?;
    sync_directory(output_root)?;
    Ok(manifest_path)
}

fn process_map_batch(
    lines: &[String],
    blank_node_scope: &str,
    logical_partitions: u32,
    worker_threads: usize,
    buffers: &mut [Vec<String>],
    terms: &mut Vec<String>,
) -> Result<(), SemanticCompilerError> {
    let lanes = worker_threads.min(lines.len()).max(1);
    let chunk_size = lines.len().div_ceil(lanes);
    let results = std::thread::scope(|scope| {
        let handles = lines
            .chunks(chunk_size)
            .map(|chunk| {
                scope.spawn(move || {
                    let mut output = Vec::with_capacity(chunk.len());
                    for line in chunk {
                        let mut parser = RdfParser::from_format(RdfFormat::NQuads)
                            .for_slice(line.as_bytes());
                        let quad = parser
                            .next()
                            .ok_or_else(|| {
                                SemanticCompilerError::Rdf("empty N-Quads statement".to_owned())
                            })?
                            .map_err(|error| SemanticCompilerError::Rdf(error.to_string()))?;
                        if parser.next().is_some() {
                            return Err(SemanticCompilerError::Rdf(
                                "decoded line contains multiple N-Quads statements".to_owned(),
                            ));
                        }
                        let scoped = scope_quad(quad, blank_node_scope)?;
                        let canonical = format!("{scoped}\n");
                        let partition = partition_for(canonical.as_bytes(), logical_partitions)?;
                        let mut dictionary_terms = Vec::with_capacity(4);
                        collect_dictionary_terms(&scoped, &mut dictionary_terms);
                        output.push((partition, canonical, dictionary_terms));
                    }
                    Ok::<_, SemanticCompilerError>(output)
                })
            })
            .collect::<Vec<_>>();
        handles
            .into_iter()
            .map(|handle| {
                handle.join().map_err(|_| {
                    SemanticCompilerError::Contract("map parser lane terminated".to_owned())
                })?
            })
            .collect::<Result<Vec<_>, SemanticCompilerError>>()
    })?;
    for (partition, line, dictionary_terms) in results.into_iter().flatten() {
        let index = usize::try_from(partition).map_err(|_| {
            SemanticCompilerError::Contract("partition index overflow".to_owned())
        })?;
        buffers[index].push(line);
        terms.extend(dictionary_terms);
    }
    Ok(())
}

/// Verify all map completions and build one canonical dense RDF dictionary.
pub fn finalize_dictionary(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    map_manifest_paths: &[PathBuf],
    output_root: &Path,
) -> Result<PathBuf, SemanticCompilerError> {
    validate_handoff(handoff)?;
    require_sha256(handoff_sha256)?;
    let maps = load_complete_maps(handoff, handoff_sha256, map_manifest_paths)?;
    ensure_new_root(output_root)?;
    let mut term_paths = Vec::new();
    let mut completion_hasher = Sha256::new();
    completion_hasher.update(b"ngkg-semantic-map-completion-set-v1\0");
    for (path, manifest) in &maps {
        completion_hasher.update(manifest.fragment_ordinal.to_be_bytes());
        completion_hasher.update(decode_sha256(&sha256_path(path)?)?);
        let parent = path.parent().ok_or_else(|| {
            SemanticCompilerError::Contract("map manifest has no parent".to_owned())
        })?;
        for run in &manifest.term_runs {
            let run_path = safe_join(parent, &run.relative_path)?;
            verify_file(&run_path, &run.sha256, Some(run.bytes))?;
            term_paths.push(run_path);
        }
    }
    let dictionary_path = output_root.join("dictionary.tsv");
    let term_count = merge_terms_to_dictionary(&term_paths, &dictionary_path)?;
    let dictionary_sha256 = sha256_path(&dictionary_path)?;
    let guid_dictionary_path = output_root.join("guid-dictionary.tsv");
    let entity_count = write_guid_dictionary(
        &dictionary_path,
        &guid_dictionary_path,
        handoff.dataset_id,
    )?;
    let manifest = DictionaryManifest {
        format_version: SEMANTIC_COMPILER_FORMAT_VERSION,
        dataset_id: handoff.dataset_id,
        snapshot_id: handoff.target_snapshot_id,
        compiler_handoff_sha256: handoff_sha256.to_owned(),
        map_completion_set_sha256: hex::encode(completion_hasher.finalize()),
        dictionary_path: "dictionary.tsv".to_owned(),
        dictionary_sha256,
        term_count,
        guid_dictionary_path: "guid-dictionary.tsv".to_owned(),
        guid_dictionary_sha256: sha256_path(&guid_dictionary_path)?,
        entity_count,
        verified_map_completions: handoff.total_objects,
    };
    let path = output_root.join("dictionary-manifest.json");
    write_json_new(&path, &manifest)?;
    sync_directory(output_root)?;
    Ok(path)
}

/// Reduce every mapped run for one logical partition into query storage artifacts.
#[allow(clippy::too_many_arguments)]
pub fn reduce_partition(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    map_manifest_paths: &[PathBuf],
    dictionary_manifest_path: &Path,
    dictionary_manifest_sha256: &str,
    partition_index: u32,
    output_root: &Path,
    limits: ReduceLimits,
) -> Result<PathBuf, SemanticCompilerError> {
    validate_handoff(handoff)?;
    if partition_index >= handoff.logical_partitions
        || limits.max_input_runs == 0
        || limits.max_partition_quads == 0
        || limits.parquet_row_group_rows == 0
    {
        return Err(SemanticCompilerError::Contract(
            "partition index or reducer limits are invalid".to_owned(),
        ));
    }
    let maps = load_complete_maps(handoff, handoff_sha256, map_manifest_paths)?;
    verify_file(dictionary_manifest_path, dictionary_manifest_sha256, None)?;
    let dictionary_manifest: DictionaryManifest =
        serde_json::from_slice(&fs::read(dictionary_manifest_path)?)?;
    if dictionary_manifest.compiler_handoff_sha256 != handoff_sha256
        || dictionary_manifest.verified_map_completions != handoff.total_objects
    {
        return Err(SemanticCompilerError::Contract(
            "dictionary manifest is not bound to the complete map barrier".to_owned(),
        ));
    }
    let dictionary_root = dictionary_manifest_path.parent().ok_or_else(|| {
        SemanticCompilerError::Contract("dictionary manifest has no parent".to_owned())
    })?;
    let dictionary_path = safe_join(dictionary_root, &dictionary_manifest.dictionary_path)?;
    verify_file(
        &dictionary_path,
        &dictionary_manifest.dictionary_sha256,
        None,
    )?;
    let mut fact_paths = Vec::new();
    for (path, manifest) in &maps {
        let parent = path.parent().ok_or_else(|| {
            SemanticCompilerError::Contract("map manifest has no parent".to_owned())
        })?;
        if let Some(runs) = manifest.fact_runs.get(&partition_index) {
            for run in runs {
                let run_path = safe_join(parent, &run.relative_path)?;
                verify_file(&run_path, &run.sha256, Some(run.bytes))?;
                fact_paths.push(run_path);
            }
        }
    }
    if fact_paths.len() > limits.max_input_runs {
        return Err(SemanticCompilerError::Contract(
            "partition fan-in exceeds reducer run ceiling".to_owned(),
        ));
    }
    ensure_new_root(output_root)?;
    let canonical_path = output_root.join("facts.nq");
    let shuffle_merge_root = output_root.join("shuffle-merge");
    let (fact_count, duplicate_fact_count) = hierarchical_merge_unique(
        &fact_paths,
        &canonical_path,
        limits.max_partition_quads,
        &shuffle_merge_root,
    )?;
    if shuffle_merge_root.exists() {
        fs::remove_dir_all(&shuffle_merge_root)?;
    }
    let dictionary = build_partition_dictionary(
        &canonical_path,
        &dictionary_path,
        &output_root.join("dictionary-work"),
        limits.parquet_row_group_rows,
    )?;
    let parquet_path = output_root.join("facts.parquet");
    let adjacency_forward_path = output_root.join("adjacency-forward.tsv");
    let adjacency_reverse_path = output_root.join("adjacency-reverse.tsv");
    let semantic_index_path = output_root.join("semantic-index.tsv");
    let graph_inventory_path = output_root.join("graph-inventory.json");
    let output = build_partition_artifacts(
        &canonical_path,
        &dictionary,
        &parquet_path,
        &adjacency_forward_path,
        &adjacency_reverse_path,
        &semantic_index_path,
        partition_index,
        limits.parquet_row_group_rows,
    )?;
    fs::remove_dir_all(output_root.join("dictionary-work"))?;
    if output.fact_count != fact_count {
        return Err(SemanticCompilerError::Contract(
            "Parquet row count differs from canonical partition".to_owned(),
        ));
    }
    write_json_new(&graph_inventory_path, &output.graph_inventory)?;
    let artifacts = [
        "facts.nq",
        "facts.parquet",
        "adjacency-forward.tsv",
        "adjacency-reverse.tsv",
        "semantic-index.tsv",
        "graph-inventory.json",
    ]
    .into_iter()
    .map(|name| artifact(output_root, name))
    .collect::<Result<Vec<_>, _>>()?;
    let partition_id = partition_identity(
        handoff.dataset_id,
        handoff.target_snapshot_id,
        &handoff.aggregate_source_sha256,
        partition_index,
    );
    let manifest = SemanticPartitionManifest {
        format_version: SEMANTIC_COMPILER_FORMAT_VERSION,
        dataset_id: handoff.dataset_id,
        snapshot_id: handoff.target_snapshot_id,
        compiler_handoff_sha256: handoff_sha256.to_owned(),
        dictionary_sha256: dictionary_manifest.dictionary_sha256,
        partition_index,
        partition_id,
        input_run_count: u32::try_from(fact_paths.len()).map_err(|_| {
            SemanticCompilerError::Contract("input run count overflow".to_owned())
        })?,
        fact_count,
        duplicate_fact_count,
        edge_count: output.edge_count,
        class_assertion_count: output.class_assertion_count,
        artifacts,
        graph_inventory: output.graph_inventory,
        semantic_content_sha256: sha256_path(&canonical_path)?,
    };
    let manifest_path = output_root.join("semantic-partition.json");
    write_json_new(&manifest_path, &manifest)?;
    sync_directory(output_root)?;
    Ok(manifest_path)
}

/// Prove exact partition coverage and publish one inactive semantic root.
pub fn finalize_semantic_root(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    dictionary_manifest_path: &Path,
    dictionary_manifest_sha256: &str,
    partition_manifest_paths: &[PathBuf],
    output_root: &Path,
) -> Result<PathBuf, SemanticCompilerError> {
    finalize_semantic_root_inner(
        handoff,
        handoff_sha256,
        dictionary_manifest_path,
        dictionary_manifest_sha256,
        partition_manifest_paths,
        output_root,
        true,
    )
}

/// Finalize partition manifests whose artifacts were independently verified in
/// immutable object storage. This prevents the barrier pod from downloading all
/// Parquet payloads a second time merely to reproduce worker checksums.
pub fn finalize_committed_semantic_root(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    dictionary_manifest_path: &Path,
    dictionary_manifest_sha256: &str,
    partition_manifest_paths: &[PathBuf],
    output_root: &Path,
) -> Result<PathBuf, SemanticCompilerError> {
    finalize_semantic_root_inner(
        handoff,
        handoff_sha256,
        dictionary_manifest_path,
        dictionary_manifest_sha256,
        partition_manifest_paths,
        output_root,
        false,
    )
}

#[allow(clippy::too_many_arguments)]
fn finalize_semantic_root_inner(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    dictionary_manifest_path: &Path,
    dictionary_manifest_sha256: &str,
    partition_manifest_paths: &[PathBuf],
    output_root: &Path,
    verify_local_artifacts: bool,
) -> Result<PathBuf, SemanticCompilerError> {
    validate_handoff(handoff)?;
    require_sha256(handoff_sha256)?;
    verify_file(dictionary_manifest_path, dictionary_manifest_sha256, None)?;
    let dictionary: DictionaryManifest =
        serde_json::from_slice(&fs::read(dictionary_manifest_path)?)?;
    if dictionary.format_version != SEMANTIC_COMPILER_FORMAT_VERSION
        || dictionary.dataset_id != handoff.dataset_id
        || dictionary.snapshot_id != handoff.target_snapshot_id
        || dictionary.compiler_handoff_sha256 != handoff_sha256
        || dictionary.verified_map_completions != handoff.total_objects
    {
        return Err(SemanticCompilerError::Contract(
            "dictionary is not bound to handoff".to_owned(),
        ));
    }
    require_sha256(&dictionary.dictionary_sha256)?;
    require_sha256(&dictionary.guid_dictionary_sha256)?;
    if verify_local_artifacts {
        let root = dictionary_manifest_path.parent().ok_or_else(|| {
            SemanticCompilerError::Contract("dictionary manifest has no parent".to_owned())
        })?;
        verify_file(
            &safe_join(root, &dictionary.dictionary_path)?,
            &dictionary.dictionary_sha256,
            None,
        )?;
        verify_file(
            &safe_join(root, &dictionary.guid_dictionary_path)?,
            &dictionary.guid_dictionary_sha256,
            None,
        )?;
    }
    if partition_manifest_paths.len()
        != usize::try_from(handoff.logical_partitions).unwrap_or(usize::MAX)
    {
        return Err(SemanticCompilerError::Contract(
            "semantic partition barrier is incomplete".to_owned(),
        ));
    }
    let mut partitions = Vec::new();
    let mut observed = BTreeSet::new();
    let mut fact_count = 0_u64;
    let mut duplicate_fact_count = 0_u64;
    let mut edge_count = 0_u64;
    let mut class_assertion_count = 0_u64;
    let mut graph_counts = BTreeMap::<(String, u64, GraphRole, bool, bool), u64>::new();
    let mut semantic = Sha256::new();
    semantic.update(b"ngkg-semantic-compilation-root-v1\0");
    for path in partition_manifest_paths {
        let manifest: SemanticPartitionManifest = serde_json::from_slice(&fs::read(path)?)?;
        validate_partition_manifest(
            &manifest,
            path,
            handoff,
            handoff_sha256,
            &dictionary.dictionary_sha256,
            verify_local_artifacts,
        )?;
        if !observed.insert(manifest.partition_index) {
            return Err(SemanticCompilerError::Contract(
                "duplicate semantic partition completion".to_owned(),
            ));
        }
        fact_count = checked_add(fact_count, manifest.fact_count, "fact")?;
        duplicate_fact_count = checked_add(
            duplicate_fact_count,
            manifest.duplicate_fact_count,
            "duplicate fact",
        )?;
        edge_count = checked_add(edge_count, manifest.edge_count, "edge")?;
        class_assertion_count = checked_add(
            class_assertion_count,
            manifest.class_assertion_count,
            "class assertion",
        )?;
        for graph in &manifest.graph_inventory {
            let key = (
                graph.graph_term.clone(),
                graph.graph_id,
                graph.role,
                graph.union_default_candidate,
                graph.asserted_ontology_candidate,
            );
            let count = graph_counts.entry(key).or_insert(0);
            *count = checked_add(*count, graph.quad_count, "graph quad")?;
        }
        semantic.update(manifest.partition_index.to_be_bytes());
        semantic.update(decode_sha256(&manifest.semantic_content_sha256)?);
        partitions.push(PartitionReference {
            partition_index: manifest.partition_index,
            partition_id: manifest.partition_id,
            manifest_path: path.to_string_lossy().into_owned(),
            manifest_sha256: sha256_path(path)?,
            fact_count: manifest.fact_count,
        });
    }
    let expected = (0..handoff.logical_partitions).collect::<BTreeSet<_>>();
    if observed != expected {
        return Err(SemanticCompilerError::Contract(
            "semantic partitions do not exactly cover the layout".to_owned(),
        ));
    }
    partitions.sort_unstable_by_key(|value| value.partition_index);
    let graph_inventory = graph_counts
        .into_iter()
        .map(
            |((graph_term, graph_id, role, union_default_candidate, asserted), quad_count)| {
                GraphInventoryEntry {
                    graph_term,
                    graph_id,
                    role,
                    quad_count,
                    union_default_candidate,
                    asserted_ontology_candidate: asserted,
                    qualification_required: true,
                }
            },
        )
        .collect::<Vec<_>>();
    let union_default_candidates = graph_inventory
        .iter()
        .filter(|value| value.union_default_candidate)
        .map(|value| value.graph_term.clone())
        .collect::<Vec<_>>();
    let asserted_ontology_candidates = graph_inventory
        .iter()
        .filter(|value| value.asserted_ontology_candidate)
        .map(|value| value.graph_term.clone())
        .collect::<Vec<_>>();
    ensure_new_root(output_root)?;
    let root = SemanticCompilationRoot {
        format_version: SEMANTIC_COMPILER_FORMAT_VERSION,
        tenant_id: handoff.tenant_id,
        dataset_id: handoff.dataset_id,
        operation_id: handoff.operation_id,
        snapshot_id: handoff.target_snapshot_id,
        compiler_handoff_sha256: handoff_sha256.to_owned(),
        aggregate_source_sha256: handoff.aggregate_source_sha256.clone(),
        dictionary_manifest_path: dictionary_manifest_path.to_string_lossy().into_owned(),
        dictionary_manifest_sha256: dictionary_manifest_sha256.to_owned(),
        logical_partitions: handoff.logical_partitions,
        partitions,
        fact_count,
        duplicate_fact_count,
        edge_count,
        class_assertion_count,
        graph_inventory,
        union_default_candidates,
        asserted_ontology_candidates,
        authorization_state: "unqualified".to_owned(),
        qualification_state: "pending-owl2-dl-snapshot-qualification".to_owned(),
        publication_state: "inactive".to_owned(),
        semantic_content_sha256: hex::encode(semantic.finalize()),
    };
    let path = output_root.join("semantic-compilation-root.json");
    write_json_new(&path, &root)?;
    sync_directory(output_root)?;
    Ok(path)
}

#[derive(Default)]
struct PartitionOutput {
    fact_count: u64,
    edge_count: u64,
    class_assertion_count: u64,
    graph_inventory: Vec<GraphInventoryEntry>,
}

#[allow(clippy::too_many_arguments)]
fn build_partition_artifacts(
    canonical_path: &Path,
    dictionary: &BTreeMap<String, u64>,
    parquet_path: &Path,
    forward_path: &Path,
    reverse_path: &Path,
    index_path: &Path,
    partition_index: u32,
    row_group_rows: usize,
) -> Result<PartitionOutput, SemanticCompilerError> {
    let schema = Arc::new(Schema::new(vec![
        Field::new("subject_id64", DataType::UInt64, false),
        Field::new("predicate_id64", DataType::UInt64, false),
        Field::new("object_kind", DataType::UInt8, false),
        Field::new("object_id64", DataType::UInt64, false),
        Field::new("graph_id64", DataType::UInt64, false),
        Field::new("partition_id", DataType::UInt64, false),
        Field::new("canonical_nquad", DataType::Utf8, false),
    ]));
    let properties = WriterProperties::builder()
        .set_max_row_group_size(row_group_rows)
        .build();
    let mut parquet = ArrowWriter::try_new(create_new(parquet_path)?, Arc::clone(&schema), Some(properties))?;
    let run_root = forward_path
        .parent()
        .ok_or_else(|| SemanticCompilerError::Contract("adjacency path has no parent".to_owned()))?
        .join("adjacency-runs");
    fs::create_dir_all(&run_root)?;
    let mut forward_buffer = Vec::<String>::with_capacity(row_group_rows);
    let mut reverse_buffer = Vec::<String>::with_capacity(row_group_rows);
    let mut forward_runs = Vec::<PathBuf>::new();
    let mut reverse_runs = Vec::<PathBuf>::new();
    let mut adjacency_run = 0_u32;
    let mut index_buffer = Vec::<String>::with_capacity(row_group_rows);
    let mut index_runs = Vec::<PathBuf>::new();
    let mut index_run = 0_u32;
    let mut subject_ids = Vec::with_capacity(row_group_rows);
    let mut predicate_ids = Vec::with_capacity(row_group_rows);
    let mut object_kinds = Vec::with_capacity(row_group_rows);
    let mut object_ids = Vec::with_capacity(row_group_rows);
    let mut graph_ids = Vec::with_capacity(row_group_rows);
    let mut lines = Vec::with_capacity(row_group_rows);
    let mut graph_counts = BTreeMap::<(String, u64), u64>::new();
    let rdf_type = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
    let mut output = PartitionOutput::default();
    let parser = RdfParser::from_format(RdfFormat::NQuads)
        .for_reader(BufReader::new(File::open(canonical_path)?));
    for parsed in parser {
        let quad = parsed.map_err(|error| SemanticCompilerError::Rdf(error.to_string()))?;
        let subject = dictionary_id(dictionary, &subject_key(&quad.subject))?;
        let predicate = dictionary_id(dictionary, &format!("N\t{}", quad.predicate.as_str()))?;
        let (object_kind, object_key) = match &quad.object {
            Term::NamedNode(node) => (1_u8, format!("N\t{}", node.as_str())),
            Term::BlankNode(node) => (2_u8, format!("B\t{}", node.as_str())),
            Term::Literal(literal) => (3_u8, format!("L\t{literal}")),
        };
        let object = dictionary_id(dictionary, &object_key)?;
        let graph_key = graph_key(&quad.graph_name);
        let graph = dictionary_id(dictionary, &graph_key)?;
        *graph_counts.entry((graph_key, graph)).or_insert(0) += 1;
        index_buffer.push(format!(
            "predicate\t{predicate:020}\t{subject:020}\t{object_kind}\t{object:020}\t{graph:020}"
        ));
        if quad.predicate.as_str() == rdf_type {
            index_buffer.push(format!(
                "class\t{object:020}\t{subject:020}\t{graph:020}"
            ));
            output.class_assertion_count = checked_add(
                output.class_assertion_count,
                1,
                "class assertion",
            )?;
        }
        if index_buffer.len() >= row_group_rows {
            flush_index_run(
                &run_root,
                &mut index_buffer,
                &mut index_runs,
                &mut index_run,
            )?;
        }
        // SPARQL paths may end at a literal for a consuming final step. Literals
        // cannot be subjects of a following step, but omitting them here made
        // `:p` and reverse-path evaluation incomplete. Dense IDs retain RDF-term
        // kind in the snapshot dictionary, so the fixed-width adjacency format
        // can safely index every RDF triple without adding a new column.
        forward_buffer.push(format!(
            "{subject:020}\t{predicate:020}\t{object:020}\t{graph:020}"
        ));
        reverse_buffer.push(format!(
            "{object:020}\t{predicate:020}\t{subject:020}\t{graph:020}"
        ));
        output.edge_count = checked_add(output.edge_count, 1, "edge")?;
        if forward_buffer.len() == row_group_rows {
            flush_adjacency_runs(
                &run_root,
                &mut forward_buffer,
                &mut reverse_buffer,
                &mut forward_runs,
                &mut reverse_runs,
                &mut adjacency_run,
            )?;
        }
        subject_ids.push(subject);
        predicate_ids.push(predicate);
        object_kinds.push(object_kind);
        object_ids.push(object);
        graph_ids.push(graph);
        lines.push(format!("{quad}"));
        output.fact_count = checked_add(output.fact_count, 1, "fact")?;
        if subject_ids.len() == row_group_rows {
            write_parquet_batch(
                &mut parquet,
                &schema,
                partition_index,
                &mut subject_ids,
                &mut predicate_ids,
                &mut object_kinds,
                &mut object_ids,
                &mut graph_ids,
                &mut lines,
            )?;
        }
    }
    if !subject_ids.is_empty() {
        write_parquet_batch(
            &mut parquet,
            &schema,
            partition_index,
            &mut subject_ids,
            &mut predicate_ids,
            &mut object_kinds,
            &mut object_ids,
            &mut graph_ids,
            &mut lines,
        )?;
    }
    parquet.close()?;
    flush_adjacency_runs(
        &run_root,
        &mut forward_buffer,
        &mut reverse_buffer,
        &mut forward_runs,
        &mut reverse_runs,
        &mut adjacency_run,
    )?;
    let (forward_count, _) = hierarchical_merge_unique(
        &forward_runs,
        forward_path,
        u64::MAX,
        &run_root.join("forward-merge"),
    )?;
    let (reverse_count, _) = hierarchical_merge_unique(
        &reverse_runs,
        reverse_path,
        u64::MAX,
        &run_root.join("reverse-merge"),
    )?;
    if forward_count != output.edge_count || reverse_count != output.edge_count {
        return Err(SemanticCompilerError::Contract(
            "adjacency indexes differ from RDF resource-edge count".to_owned(),
        ));
    }
    flush_index_run(
        &run_root,
        &mut index_buffer,
        &mut index_runs,
        &mut index_run,
    )?;
    let _ = hierarchical_merge_unique(
        &index_runs,
        index_path,
        u64::MAX,
        &run_root.join("index-merge"),
    )?;
    fs::remove_dir_all(run_root)?;
    output.graph_inventory = graph_counts
        .into_iter()
        .map(|((term, id), count)| graph_inventory_entry(term, id, count))
        .collect();
    Ok(output)
}

fn flush_index_run(
    root: &Path,
    rows: &mut Vec<String>,
    runs: &mut Vec<PathBuf>,
    ordinal: &mut u32,
) -> Result<(), SemanticCompilerError> {
    if rows.is_empty() {
        return Ok(());
    }
    rows.sort_unstable();
    rows.dedup();
    let path = root.join(format!("index-{ordinal:08}.tsv"));
    write_lines(&path, rows.iter().map(String::as_str))?;
    runs.push(path);
    rows.clear();
    *ordinal = ordinal.checked_add(1).ok_or_else(|| {
        SemanticCompilerError::Contract("semantic index run ordinal overflow".to_owned())
    })?;
    Ok(())
}

fn flush_adjacency_runs(
    root: &Path,
    forward: &mut Vec<String>,
    reverse: &mut Vec<String>,
    forward_runs: &mut Vec<PathBuf>,
    reverse_runs: &mut Vec<PathBuf>,
    ordinal: &mut u32,
) -> Result<(), SemanticCompilerError> {
    if forward.is_empty() {
        return Ok(());
    }
    forward.sort_unstable();
    forward.dedup();
    reverse.sort_unstable();
    reverse.dedup();
    let forward_path = root.join(format!("forward-{ordinal:08}.tsv"));
    let reverse_path = root.join(format!("reverse-{ordinal:08}.tsv"));
    write_lines(&forward_path, forward.iter().map(String::as_str))?;
    write_lines(&reverse_path, reverse.iter().map(String::as_str))?;
    forward_runs.push(forward_path);
    reverse_runs.push(reverse_path);
    forward.clear();
    reverse.clear();
    *ordinal = ordinal.checked_add(1).ok_or_else(|| {
        SemanticCompilerError::Contract("adjacency run ordinal overflow".to_owned())
    })?;
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn write_parquet_batch(
    writer: &mut ArrowWriter<File>,
    schema: &Arc<Schema>,
    partition_index: u32,
    subjects: &mut Vec<u64>,
    predicates: &mut Vec<u64>,
    object_kinds: &mut Vec<u8>,
    objects: &mut Vec<u64>,
    graphs: &mut Vec<u64>,
    lines: &mut Vec<String>,
) -> Result<(), SemanticCompilerError> {
    let count = subjects.len();
    let columns: Vec<ArrayRef> = vec![
        Arc::new(UInt64Array::from(std::mem::take(subjects))),
        Arc::new(UInt64Array::from(std::mem::take(predicates))),
        Arc::new(UInt8Array::from(std::mem::take(object_kinds))),
        Arc::new(UInt64Array::from(std::mem::take(objects))),
        Arc::new(UInt64Array::from(std::mem::take(graphs))),
        Arc::new(UInt64Array::from(vec![u64::from(partition_index); count])),
        Arc::new(StringArray::from(std::mem::take(lines))),
    ];
    writer.write(&RecordBatch::try_new(Arc::clone(schema), columns)?)?;
    Ok(())
}

fn graph_inventory_entry(term: String, id: u64, count: u64) -> GraphInventoryEntry {
    let lexical = term.strip_prefix("N\t").unwrap_or(&term);
    let role = if term == "D\t" {
        GraphRole::PhysicalDefault
    } else if lexical.starts_with(GRAPH_NAMESPACE) && lexical.ends_with("/semkg") {
        GraphRole::AssertedOntologyCandidate
    } else if lexical.starts_with(GRAPH_NAMESPACE) && lexical.ends_with("/closure") {
        GraphRole::ClosureArtifact
    } else if lexical.starts_with(GRAPH_NAMESPACE) && lexical.ends_with("/provenance") {
        GraphRole::ProvenanceArtifact
    } else {
        GraphRole::NamedRdf
    };
    let asserted = role == GraphRole::AssertedOntologyCandidate;
    GraphInventoryEntry {
        graph_term: lexical.to_owned(),
        graph_id: id,
        role,
        quad_count: count,
        union_default_candidate: asserted,
        asserted_ontology_candidate: asserted,
        qualification_required: true,
    }
}

fn validate_partition_manifest(
    manifest: &SemanticPartitionManifest,
    path: &Path,
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    dictionary_sha256: &str,
    verify_artifacts: bool,
) -> Result<(), SemanticCompilerError> {
    if manifest.format_version != SEMANTIC_COMPILER_FORMAT_VERSION
        || manifest.dataset_id != handoff.dataset_id
        || manifest.snapshot_id != handoff.target_snapshot_id
        || manifest.compiler_handoff_sha256 != handoff_sha256
        || manifest.dictionary_sha256 != dictionary_sha256
        || manifest.partition_index >= handoff.logical_partitions
        || manifest.partition_id
            != partition_identity(
                handoff.dataset_id,
                handoff.target_snapshot_id,
                &handoff.aggregate_source_sha256,
                manifest.partition_index,
            )
    {
        return Err(SemanticCompilerError::Contract(
            "semantic partition identity is invalid".to_owned(),
        ));
    }
    require_sha256(&manifest.semantic_content_sha256)?;
    if verify_artifacts {
        let parent = path.parent().ok_or_else(|| {
            SemanticCompilerError::Contract("partition manifest has no parent".to_owned())
        })?;
        for artifact in &manifest.artifacts {
            let artifact_path = safe_join(parent, &artifact.relative_path)?;
            verify_file(&artifact_path, &artifact.sha256, Some(artifact.bytes))?;
        }
    }
    Ok(())
}

fn load_complete_maps(
    handoff: &CompilerHandoffManifest,
    handoff_sha256: &str,
    paths: &[PathBuf],
) -> Result<Vec<(PathBuf, FragmentMapManifest)>, SemanticCompilerError> {
    if paths.len() != handoff.fragments.len() {
        return Err(SemanticCompilerError::Contract(
            "map completion barrier is incomplete".to_owned(),
        ));
    }
    let mut maps = BTreeMap::new();
    for path in paths {
        let manifest: FragmentMapManifest = serde_json::from_slice(&fs::read(path)?)?;
        if manifest.format_version != SEMANTIC_COMPILER_FORMAT_VERSION
            || manifest.dataset_id != handoff.dataset_id
            || manifest.snapshot_id != handoff.target_snapshot_id
            || manifest.compiler_handoff_sha256 != handoff_sha256
            || manifest.aggregate_source_sha256 != handoff.aggregate_source_sha256
            || manifest.logical_partitions != handoff.logical_partitions
        {
            return Err(SemanticCompilerError::Contract(
                "map manifest identity is invalid".to_owned(),
            ));
        }
        let fragment = handoff
            .fragments
            .get(usize::try_from(manifest.fragment_ordinal).unwrap_or(usize::MAX))
            .filter(|value| value.ordinal == manifest.fragment_ordinal)
            .ok_or_else(|| SemanticCompilerError::Contract("map fragment is absent".to_owned()))?;
        if manifest.fragment_sha256 != fragment.sha256
            || manifest.blank_node_scope != fragment.blank_node_scope
            || manifest.input_quad_count != fragment.quad_count
        {
            return Err(SemanticCompilerError::Contract(
                "map manifest does not match verified fragment".to_owned(),
            ));
        }
        if maps
            .insert(manifest.fragment_ordinal, (path.clone(), manifest))
            .is_some()
        {
            return Err(SemanticCompilerError::Contract(
                "duplicate map completion".to_owned(),
            ));
        }
    }
    if maps.keys().copied().collect::<BTreeSet<_>>()
        != (0..handoff.total_objects).collect::<BTreeSet<_>>()
    {
        return Err(SemanticCompilerError::Contract(
            "map completions do not exactly cover fragments".to_owned(),
        ));
    }
    Ok(maps.into_values().collect())
}

fn scope_quad(quad: Quad, scope: &str) -> Result<Quad, SemanticCompilerError> {
    let subject = match quad.subject {
        Subject::NamedNode(node) => Subject::NamedNode(node),
        Subject::BlankNode(node) => Subject::BlankNode(scoped_blank_node(scope, &node)?),
    };
    let object = match quad.object {
        Term::NamedNode(node) => Term::NamedNode(node),
        Term::BlankNode(node) => Term::BlankNode(scoped_blank_node(scope, &node)?),
        Term::Literal(literal) => Term::Literal(literal),
    };
    let graph_name = match quad.graph_name {
        GraphName::NamedNode(node) => GraphName::NamedNode(node),
        GraphName::BlankNode(node) => GraphName::BlankNode(scoped_blank_node(scope, &node)?),
        GraphName::DefaultGraph => GraphName::DefaultGraph,
    };
    Ok(Quad::new(subject, quad.predicate, object, graph_name))
}

fn scoped_blank_node(scope: &str, node: &BlankNode) -> Result<BlankNode, SemanticCompilerError> {
    let mut digest = Sha256::new();
    digest.update(b"ngkg-object-scoped-blank-node-v1\0");
    digest.update(scope.as_bytes());
    digest.update(b"\0");
    digest.update(node.as_str().as_bytes());
    BlankNode::new(format!("c8{}", hex::encode(digest.finalize())))
        .map_err(|error| SemanticCompilerError::Rdf(error.to_string()))
}

fn collect_dictionary_terms(quad: &Quad, output: &mut Vec<String>) {
    output.push(subject_key(&quad.subject));
    output.push(format!("N\t{}", quad.predicate.as_str()));
    output.push(match &quad.object {
        Term::NamedNode(node) => format!("N\t{}", node.as_str()),
        Term::BlankNode(node) => format!("B\t{}", node.as_str()),
        Term::Literal(literal) => format!("L\t{literal}"),
    });
    output.push(graph_key(&quad.graph_name));
}

fn subject_key(subject: &Subject) -> String {
    match subject {
        Subject::NamedNode(node) => format!("N\t{}", node.as_str()),
        Subject::BlankNode(node) => format!("B\t{}", node.as_str()),
    }
}

fn graph_key(graph: &GraphName) -> String {
    match graph {
        GraphName::NamedNode(node) => format!("N\t{}", node.as_str()),
        GraphName::BlankNode(node) => format!("B\t{}", node.as_str()),
        GraphName::DefaultGraph => "D\t".to_owned(),
    }
}

fn flush_fact_buffers(
    root: &Path,
    buffers: &mut [Vec<String>],
    manifests: &mut BTreeMap<u32, Vec<RunArtifact>>,
    run_ordinal: &mut u32,
) -> Result<(), SemanticCompilerError> {
    for (partition, buffer) in buffers.iter_mut().enumerate() {
        if buffer.is_empty() {
            continue;
        }
        buffer.sort_unstable();
        buffer.dedup();
        let index = u32::try_from(partition)
            .map_err(|_| SemanticCompilerError::Contract("partition overflow".to_owned()))?;
        let relative = format!("fact-runs/part-{index:05}/run-{:08}.nq", *run_ordinal);
        let path = safe_join(root, &relative)?;
        write_lines(&path, buffer.iter().map(String::as_str))?;
        manifests.entry(index).or_default().push(artifact(root, &relative)?);
        *run_ordinal = run_ordinal.checked_add(1).ok_or_else(|| {
            SemanticCompilerError::Contract("fact run ordinal overflow".to_owned())
        })?;
        buffer.clear();
    }
    Ok(())
}

fn flush_term_buffer(
    root: &Path,
    buffer: &mut Vec<String>,
    manifests: &mut Vec<RunArtifact>,
    ordinal: &mut u32,
) -> Result<(), SemanticCompilerError> {
    if buffer.is_empty() {
        return Ok(());
    }
    buffer.sort_unstable();
    buffer.dedup();
    let relative = format!("term-runs/run-{:08}.txt", *ordinal);
    let path = safe_join(root, &relative)?;
    write_lines(&path, buffer.iter().map(String::as_str))?;
    manifests.push(artifact(root, &relative)?);
    *ordinal = ordinal.checked_add(1).ok_or_else(|| {
        SemanticCompilerError::Contract("term run ordinal overflow".to_owned())
    })?;
    buffer.clear();
    Ok(())
}

fn merge_terms_to_dictionary(
    inputs: &[PathBuf],
    output: &Path,
) -> Result<u64, SemanticCompilerError> {
    let parent = output.parent().ok_or_else(|| {
        SemanticCompilerError::Contract("dictionary output has no parent".to_owned())
    })?;
    let merge_root = parent.join("dictionary-merge");
    let terms_path = parent.join("dictionary-terms.txt");
    let _ = hierarchical_merge_unique(inputs, &terms_path, u64::MAX, &merge_root)?;
    let mut writer = BufWriter::new(create_new(output)?);
    let mut id = 0_u64;
    for line in BufReader::new(File::open(&terms_path)?).lines() {
        writeln!(writer, "{id}\t{}", line?)?;
        id = id.checked_add(1).ok_or_else(|| {
            SemanticCompilerError::Contract("dictionary ID overflow".to_owned())
        })?;
    }
    writer.flush()?;
    writer.get_ref().sync_all()?;
    fs::remove_file(terms_path)?;
    if merge_root.exists() {
        fs::remove_dir_all(merge_root)?;
    }
    Ok(id)
}

fn write_guid_dictionary(
    dictionary_path: &Path,
    output: &Path,
    dataset_namespace: Uuid,
) -> Result<u64, SemanticCompilerError> {
    let mut writer = BufWriter::new(create_new(output)?);
    let mut count = 0_u64;
    for line in BufReader::new(File::open(dictionary_path)?).lines() {
        let line = line?;
        let (dense_id, term) = line.split_once('\t').ok_or_else(|| {
            SemanticCompilerError::Contract("dictionary row lacks dense ID".to_owned())
        })?;
        if term.starts_with("N\t") || term.starts_with("B\t") {
            let guid = Uuid::new_v5(&dataset_namespace, term.as_bytes());
            writeln!(writer, "{dense_id}\t{guid}\t{term}")?;
            count = checked_add(count, 1, "entity")?;
        }
    }
    writer.flush()?;
    writer.get_ref().sync_all()?;
    Ok(count)
}

fn merge_facts_unique(
    inputs: &[PathBuf],
    output: &Path,
    maximum: u64,
) -> Result<(u64, u64), SemanticCompilerError> {
    let mut readers = inputs
        .iter()
        .map(|path| Ok(BufReader::new(File::open(path)?).lines()))
        .collect::<Result<Vec<_>, SemanticCompilerError>>()?;
    let mut heap = BinaryHeap::<Reverse<(String, usize)>>::new();
    for (index, reader) in readers.iter_mut().enumerate() {
        if let Some(line) = reader.next() {
            heap.push(Reverse((line?, index)));
        }
    }
    let mut writer = BufWriter::new(create_new(output)?);
    let mut previous = None::<String>;
    let mut unique = 0_u64;
    let mut duplicates = 0_u64;
    while let Some(Reverse((line, index))) = heap.pop() {
        if previous.as_ref() == Some(&line) {
            duplicates = checked_add(duplicates, 1, "duplicate")?;
        } else {
            unique = checked_add(unique, 1, "fact")?;
            if unique > maximum {
                return Err(SemanticCompilerError::Contract(
                    "partition exceeded fact ceiling".to_owned(),
                ));
            }
            writeln!(writer, "{line}")?;
            previous = Some(line);
        }
        if let Some(next) = readers[index].next() {
            heap.push(Reverse((next?, index)));
        }
    }
    writer.flush()?;
    writer.get_ref().sync_all()?;
    Ok((unique, duplicates))
}

fn hierarchical_merge_unique(
    inputs: &[PathBuf],
    output: &Path,
    maximum: u64,
    work_root: &Path,
) -> Result<(u64, u64), SemanticCompilerError> {
    let mut current = inputs.to_vec();
    let mut pass = 0_u32;
    let mut duplicates = 0_u64;
    while current.len() > EXTERNAL_MERGE_FAN_IN {
        let pass_root = work_root.join(format!("pass-{pass:04}"));
        fs::create_dir_all(&pass_root)?;
        let mut next = Vec::with_capacity(current.len().div_ceil(EXTERNAL_MERGE_FAN_IN));
        for (group, chunk) in current.chunks(EXTERNAL_MERGE_FAN_IN).enumerate() {
            let path = pass_root.join(format!("run-{group:08}.txt"));
            let (_, removed) = merge_facts_unique(chunk, &path, maximum)?;
            duplicates = checked_add(duplicates, removed, "duplicate")?;
            next.push(path);
        }
        current = next;
        pass = pass.checked_add(1).ok_or_else(|| {
            SemanticCompilerError::Contract("merge pass overflow".to_owned())
        })?;
    }
    let (rows, removed) = merge_facts_unique(&current, output, maximum)?;
    duplicates = checked_add(duplicates, removed, "duplicate")?;
    Ok((rows, duplicates))
}

fn build_partition_dictionary(
    canonical_path: &Path,
    global_dictionary_path: &Path,
    work_root: &Path,
    rows_in_memory: usize,
) -> Result<BTreeMap<String, u64>, SemanticCompilerError> {
    fs::create_dir_all(work_root)?;
    let mut buffer = Vec::with_capacity(rows_in_memory);
    let mut runs = Vec::new();
    let mut ordinal = 0_u32;
    let parser = RdfParser::from_format(RdfFormat::NQuads)
        .for_reader(BufReader::new(File::open(canonical_path)?));
    for parsed in parser {
        let quad = parsed.map_err(|error| SemanticCompilerError::Rdf(error.to_string()))?;
        collect_dictionary_terms(&quad, &mut buffer);
        if buffer.len() >= rows_in_memory {
            flush_partition_term_run(work_root, &mut buffer, &mut runs, &mut ordinal)?;
        }
    }
    flush_partition_term_run(work_root, &mut buffer, &mut runs, &mut ordinal)?;
    let terms_path = work_root.join("terms.txt");
    let term_merge_root = work_root.join("term-merge");
    let _ = hierarchical_merge_unique(&runs, &terms_path, u64::MAX, &term_merge_root)?;
    if term_merge_root.exists() {
        fs::remove_dir_all(term_merge_root)?;
    }
    let mut targets = BufReader::new(File::open(terms_path)?).lines();
    let mut target = targets.next().transpose()?;
    let mut local = BTreeMap::new();
    if target.is_none() {
        return Ok(local);
    }
    let mut expected_global_id = 0_u64;
    for line in BufReader::new(File::open(global_dictionary_path)?).lines() {
        let line = line?;
        let (id, term) = line.split_once('\t').ok_or_else(|| {
            SemanticCompilerError::Contract("dictionary row lacks ID".to_owned())
        })?;
        if id.parse::<u64>().ok() != Some(expected_global_id) {
            return Err(SemanticCompilerError::Contract(
                "global dictionary is not dense".to_owned(),
            ));
        }
        expected_global_id = expected_global_id.checked_add(1).ok_or_else(|| {
            SemanticCompilerError::Contract("dictionary ID overflow".to_owned())
        })?;
        while target.as_deref().is_some_and(|value| value < term) {
            return Err(SemanticCompilerError::Contract(
                "global dictionary is missing a partition term".to_owned(),
            ));
        }
        if target.as_deref() == Some(term) {
            local.insert(term.to_owned(), expected_global_id - 1);
            target = targets.next().transpose()?;
            if target.is_none() {
                break;
            }
        }
    }
    if target.is_some() {
        return Err(SemanticCompilerError::Contract(
            "global dictionary ended before partition terms".to_owned(),
        ));
    }
    Ok(local)
}

fn flush_partition_term_run(
    root: &Path,
    buffer: &mut Vec<String>,
    runs: &mut Vec<PathBuf>,
    ordinal: &mut u32,
) -> Result<(), SemanticCompilerError> {
    if buffer.is_empty() {
        return Ok(());
    }
    buffer.sort_unstable();
    buffer.dedup();
    let path = root.join(format!("terms-{ordinal:08}.txt"));
    write_lines(&path, buffer.iter().map(String::as_str))?;
    runs.push(path);
    buffer.clear();
    *ordinal = ordinal.checked_add(1).ok_or_else(|| {
        SemanticCompilerError::Contract("partition term run overflow".to_owned())
    })?;
    Ok(())
}

fn dictionary_id(
    dictionary: &BTreeMap<String, u64>,
    key: &str,
) -> Result<u64, SemanticCompilerError> {
    dictionary.get(key).copied().ok_or_else(|| {
        SemanticCompilerError::Contract(format!("dictionary is missing term {key}"))
    })
}

fn partition_for(bytes: &[u8], count: u32) -> Result<u32, SemanticCompilerError> {
    let digest = Sha256::digest(bytes);
    let mut prefix = [0_u8; 8];
    prefix.copy_from_slice(&digest[..8]);
    let bucket = u64::from_be_bytes(prefix) % u64::from(count);
    u32::try_from(bucket)
        .map_err(|_| SemanticCompilerError::Contract("partition overflow".to_owned()))
}

fn partition_identity(
    dataset_id: Uuid,
    snapshot_id: Uuid,
    source_sha256: &str,
    partition_index: u32,
) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"ngkg-cloud-semantic-partition-v1\0");
    hasher.update(dataset_id.as_bytes());
    hasher.update(snapshot_id.as_bytes());
    hasher.update(source_sha256.as_bytes());
    hasher.update(partition_index.to_be_bytes());
    format!("semantic-{partition_index:05}-{}", &hex::encode(hasher.finalize())[..24])
}

fn valid_blank_scope(value: &str, ordinal: u32) -> bool {
    let prefix = format!("object-{ordinal:08}-");
    value
        .strip_prefix(&prefix)
        .is_some_and(|suffix| suffix.len() == 64 && suffix.bytes().all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase()))
}

fn artifact(root: &Path, relative: &str) -> Result<RunArtifact, SemanticCompilerError> {
    let path = safe_join(root, relative)?;
    let row_count = if matches!(path.extension().and_then(|value| value.to_str()), Some("nq" | "txt" | "tsv")) {
        BufReader::new(File::open(&path)?).lines().try_fold(0_u64, |count, line| {
            line?;
            count.checked_add(1).ok_or_else(|| std::io::Error::other("row count overflow"))
        })?
    } else {
        0
    };
    Ok(RunArtifact {
        relative_path: relative.to_owned(),
        sha256: sha256_path(&path)?,
        bytes: fs::metadata(path)?.len(),
        row_count,
    })
}

fn ensure_new_root(path: &Path) -> Result<(), SemanticCompilerError> {
    if path.exists() {
        return Err(SemanticCompilerError::ImmutableConflict(path.to_owned()));
    }
    fs::create_dir_all(path)?;
    Ok(())
}

fn safe_join(root: &Path, relative: &str) -> Result<PathBuf, SemanticCompilerError> {
    let candidate = Path::new(relative);
    if relative.is_empty()
        || candidate.is_absolute()
        || candidate.components().any(|component| {
            !matches!(component, std::path::Component::Normal(_))
        })
    {
        return Err(SemanticCompilerError::Contract(
            "artifact path is not a normalized relative path".to_owned(),
        ));
    }
    Ok(root.join(candidate))
}

fn write_lines<'a>(
    path: &Path,
    lines: impl Iterator<Item = &'a str>,
) -> Result<(), SemanticCompilerError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut writer = BufWriter::new(create_new(path)?);
    for line in lines {
        writer.write_all(line.as_bytes())?;
        if !line.ends_with('\n') {
            writer.write_all(b"\n")?;
        }
    }
    writer.flush()?;
    writer.get_ref().sync_all()?;
    Ok(())
}

fn write_json_new<T: Serialize>(path: &Path, value: &T) -> Result<(), SemanticCompilerError> {
    let mut writer = BufWriter::new(create_new(path)?);
    serde_json::to_writer_pretty(&mut writer, value)?;
    writer.write_all(b"\n")?;
    writer.flush()?;
    writer.get_ref().sync_all()?;
    Ok(())
}

fn create_new(path: &Path) -> Result<File, SemanticCompilerError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    Ok(OpenOptions::new().create_new(true).write(true).open(path)?)
}

fn verify_file(
    path: &Path,
    expected_sha256: &str,
    expected_bytes: Option<u64>,
) -> Result<(), SemanticCompilerError> {
    require_sha256(expected_sha256)?;
    let metadata = fs::symlink_metadata(path)?;
    if !metadata.file_type().is_file()
        || metadata.file_type().is_symlink()
        || expected_bytes.is_some_and(|expected| expected != metadata.len())
        || sha256_path(path)? != expected_sha256
    {
        return Err(SemanticCompilerError::Contract(format!(
            "artifact identity mismatch: {}",
            path.display()
        )));
    }
    Ok(())
}

/// Compute lowercase SHA-256 for one regular file.
pub fn sha256_path(path: &Path) -> Result<String, SemanticCompilerError> {
    let mut reader = BufReader::new(File::open(path)?);
    let mut hasher = Sha256::new();
    let mut buffer = vec![0_u8; 1024 * 1024];
    loop {
        let read = reader.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(hex::encode(hasher.finalize()))
}

fn require_sha256(value: &str) -> Result<(), SemanticCompilerError> {
    if value.len() != 64
        || value
            .bytes()
            .any(|byte| !byte.is_ascii_hexdigit() || byte.is_ascii_uppercase())
    {
        return Err(SemanticCompilerError::Contract(
            "SHA-256 must be lowercase hexadecimal".to_owned(),
        ));
    }
    Ok(())
}

fn decode_sha256(value: &str) -> Result<[u8; 32], SemanticCompilerError> {
    require_sha256(value)?;
    let bytes = hex::decode(value)
        .map_err(|_| SemanticCompilerError::Contract("invalid SHA-256".to_owned()))?;
    let mut output = [0_u8; 32];
    output.copy_from_slice(&bytes);
    Ok(output)
}

fn checked_add(left: u64, right: u64, label: &str) -> Result<u64, SemanticCompilerError> {
    left.checked_add(right).ok_or_else(|| {
        SemanticCompilerError::Contract(format!("{label} count overflow"))
    })
}

fn sync_directory(path: &Path) -> Result<(), SemanticCompilerError> {
    File::open(path)?.sync_all()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use sha2::{Digest, Sha256};
    use uuid::Uuid;

    use super::{
        CompilerHandoffManifest, DecodedFragment, MapLimits, ReduceLimits,
        finalize_dictionary, finalize_semantic_root, map_fragment, reduce_partition,
        sha256_path,
    };

    fn handoff(fragment: &Path, sha256: String, bytes: u64) -> CompilerHandoffManifest {
        CompilerHandoffManifest {
            format_version: 1,
            tenant_id: Uuid::from_u128(1),
            dataset_id: Uuid::from_u128(2),
            operation_id: Uuid::from_u128(3),
            target_snapshot_id: Uuid::from_u128(4),
            source_manifest_object_key: "imports/source.json".to_owned(),
            source_manifest_sha256: "1".repeat(64),
            decode_plan_object_key: "imports/decode.json".to_owned(),
            decode_plan_sha256: "2".repeat(64),
            aggregate_source_sha256: "3".repeat(64),
            logical_partitions: 2,
            decoded_format: "application/n-quads".to_owned(),
            blank_node_policy: "object-scoped-label-v1".to_owned(),
            total_objects: 1,
            total_bytes: bytes,
            total_quads: 3,
            expected_completions: 1,
            verified_completions: 1,
            completion_set_sha256: "4".repeat(64),
            fragments: vec![DecodedFragment {
                ordinal: 0,
                source_object_key: "source/example.trig".to_owned(),
                source_sha256: "5".repeat(64),
                blank_node_scope: format!("object-00000000-{}", "6".repeat(64)),
                object_key: fragment.to_string_lossy().into_owned(),
                sha256,
                bytes,
                quad_count: 3,
            }],
        }
    }

    #[test]
    fn complete_pipeline_is_topology_stable_and_inactive() -> Result<(), Box<dyn std::error::Error>> {
        let nonce = hex::encode(Sha256::digest(format!("{}", std::process::id()).as_bytes()));
        let root = std::env::temp_dir().join(format!("ngkg-semantic-compiler-{}", &nonce[..12]));
        if root.exists() {
            fs::remove_dir_all(&root)?;
        }
        fs::create_dir_all(&root)?;
        let fragment = root.join("fragment.nq");
        fs::write(
            &fragment,
            concat!(
                "_:a <https://example/p> <https://example/b> <https://c8-next-generation.io/supply/chain/semkg> .\n",
                "<https://example/b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://example/Class> <https://c8-next-generation.io/supply/chain/semkg> .\n",
                "<https://example/b> <https://example/name> \"B\" <https://c8-next-generation.io/supply/chain/provenance> .\n",
            ),
        )?;
        let fragment_sha = sha256_path(&fragment)?;
        let bytes = fs::metadata(&fragment)?.len();
        let handoff = handoff(&fragment, fragment_sha, bytes);
        let handoff_path = root.join("handoff.json");
        fs::write(&handoff_path, serde_json::to_vec_pretty(&handoff)?)?;
        let handoff_sha = sha256_path(&handoff_path)?;
        let map_path = map_fragment(
            &handoff,
            &handoff_sha,
            0,
            &fragment,
            &root.join("map"),
            MapLimits {
                max_fragment_bytes: bytes,
                max_fragment_quads: 3,
                max_rows_in_memory: 2,
                max_run_bytes: u64::MAX,
                worker_threads: 2,
            },
        )?;
        let dictionary_path = finalize_dictionary(
            &handoff,
            &handoff_sha,
            std::slice::from_ref(&map_path),
            &root.join("dictionary"),
        )?;
        let dictionary_sha = sha256_path(&dictionary_path)?;
        let mut partitions = Vec::new();
        for index in 0..2 {
            partitions.push(reduce_partition(
                &handoff,
                &handoff_sha,
                std::slice::from_ref(&map_path),
                &dictionary_path,
                &dictionary_sha,
                index,
                &root.join(format!("partition-{index}")),
                ReduceLimits {
                    max_input_runs: 16,
                    max_partition_quads: 10,
                    parquet_row_group_rows: 2,
                },
            )?);
        }
        let root_path = finalize_semantic_root(
            &handoff,
            &handoff_sha,
            &dictionary_path,
            &dictionary_sha,
            &partitions,
            &root.join("root"),
        )?;
        let compiled: super::SemanticCompilationRoot =
            serde_json::from_slice(&fs::read(root_path)?)?;
        assert_eq!(compiled.fact_count, 3);
        assert_eq!(compiled.edge_count, 3);
        assert_eq!(compiled.publication_state, "inactive");
        assert_eq!(compiled.authorization_state, "unqualified");
        assert_eq!(compiled.asserted_ontology_candidates.len(), 1);
        assert_eq!(compiled.union_default_candidates.len(), 1);
        fs::remove_dir_all(root)?;
        Ok(())
    }

    #[test]
    fn object_scoped_blank_nodes_do_not_collapse() {
        let first = super::scoped_blank_node(
            &format!("object-00000000-{}", "1".repeat(64)),
            &oxigraph::model::BlankNode::new_unchecked("x"),
        );
        let second = super::scoped_blank_node(
            &format!("object-00000001-{}", "2".repeat(64)),
            &oxigraph::model::BlankNode::new_unchecked("x"),
        );
        assert!(first.is_ok());
        assert!(second.is_ok());
        assert_ne!(first.ok(), second.ok());
    }
}
